columns: 
  - size: small
    widgets:   
      - type: markets
        title: Moedas
        markets:
          - symbol: BTC-USD
            name: Bitcoin 
 
      - type: markets
        title: BRASIL
        chart-link-template: https://www.tradingview.com/chart/?symbol={SYMBOL}
        symbol-link-template: https://www.google.com/search?tbm=nws&q={SYMBOL}
        markets:        
          - symbol: ^BVSP
            name: BOVESPA  
            symbol-link: https://www.google.com/search?tbm=nws&q=BOVESPA  
          - symbol: TOTS3.SA           
            name: Totvs 
            symbol-link: https://www.google.com/search?tbm=nws&q=Totvs
            chart-link-template: https://www.tradingview.com/chart/?symbol=TOTS3 
          - symbol: MGLU3.SA
            name: Magazine Luiza
            symbol-link: https://www.google.com/search?tbm=nws&q=Magazine+
            chart-link-template: https://www.tradingview.com/chart/?symbol=MGLU3 

      - type: markets
        title: USA
        chart-link-template: https://www.tradingview.com/chart/?symbol={SYMBOL}
        symbol-link-template: https://www.google.com/search?tbm=nws&q={SYMBOL}
        markets:      
          - symbol: NDAQ
            name: Nasdaq
            symbol-link: https://www.google.com/search?tbm=nws&q=Nasdaq
          - symbol: NVDA
            name: NVIDIA
            symbol-link: https://www.google.com/search?tbm=nws&q=NVIDIA
          - symbol: AAPL
            name: Apple
            symbol-link: https://www.google.com/search?tbm=nws&q=Apple
          - symbol: GOOGL
            name: google
            symbol-link: https://www.google.com/search?tbm=nws&q=Google
          - symbol: MSFT
            name: Microsoft
            symbol-link: https://www.google.com/search?tbm=nws&q=Microsoft
          - symbol: AMZN
            name: Amazon
            symbol-link: https://www.google.com/search?tbm=nws&q=Amazon
          - symbol: FB
            name: Meta Platforms
            symbol-link: https://www.google.com/search?tbm=nws&q=Meta+Platforms
          - symbol: TSLA
            name: Tesla
            symbol-link: https://www.google.com/search?tbm=nws&q=Tesla
          - symbol: NFLX
            name: Netflix
            symbol-link: https://www.google.com/search?tbm=nws&q=Netflix

      - type: markets
        title: ALEMANHA
        chart-link-template: https://www.tradingview.com/chart/?symbol={SYMBOL}
        symbol-link-template: https://www.google.com/search?tbm=nws&q={SYMBOL}
        markets:      
          - symbol: DAX
            name: DAX 
            symbol-link: https://www.google.com/search?tbm=nws&q=DAX
          - symbol: SAP
            name: SAP
            symbol-link: https://www.google.com/search?tbm=nws&q=SAP`

      - type: releases
        show-source-icon: true
        repositories:
          - glanceapp/glance 
          - openclaw/openclaw
          - NginxProxyManager/nginx-proxy-manager
          - alexjustesen/speedtest-tracker
          
  - size: full
    widgets: 
      - type: search 
        search-engine: perplexity
        bangs:
          - title: OpenAI
            shortcut: "!yt"
            url: https://chat.openai.com/?prompt={QUERY}        

      - type: rss 
        title: Tecnologia
        cache: 30s # 30 seconds
        style: detailed-list
        limit: 25
        single-line-titles: true
        preserve-order: false
        colapse-after-rows: 5
        feeds: 
          - url: https://g1.globo.com/rss/g1/tecnologia/
            title: G1 - Tecnologia
            limit: 25 
          - url: https://techcrunch.com/feed/
            title: TechCrunch
            limit: 25 

      - type: hacker-news
        limit: 15
        collapse-after: 5

      - type: bookmarks
        $include: bookmarks.yml

  - size: small 
    widgets:   
      - type: videos
        title: GitHub Trending
        limit: 10
        style: grid-cards
        collapse-after: 2
        collapse-after-rows: 1
        channels:
          - UC9Rrud-8CaHokDtK9FszvRg 
          
      - type: videos
        title: Fireship
        limit: 100
        style: grid-cards
        collapse-after: 6
        collapse-after-rows: 3
        channels: 
          - UCsBjURrPoezykLs9EqgamOA